from __future__ import annotations
from matplotlib.lines import Line2D
from typing import Self, Literal

LegendMode = Literal[
    "all",
    "series",
    "points",
]

class LegendMixin:
    """
    Legend management utilities.

    This mixin provides functionality for creating, collecting, and
    rendering chart legends. It automatically combines legend entries
    generated by plotting methods with custom legend items registered
    through helper methods.

    Features
    --------
    - Automatic collection of legend items from the primary axis.
    - Optional collection of legend items from a secondary axis.
    - Registration of custom legend markers.
    - Automatic removal of duplicate labels.
    - Consistent legend styling across chart types.

    Notes
    -----
    Legend entries are not created directly by this mixin. Instead,
    plotting methods register labels through Matplotlib and
    `LegendMixin` gathers them into a single legend when
    `add_legend()` is called.
    """
    
    def add_legend(
        self,
        loc: str = "upper left",
        bbox_to_anchor: tuple | None = None,
        ncol: int = 1,
        fontsize: int = 7,
        frameon: bool = True,
        edgecolor: str = "white",
        facecolor: str = "white",
        framealpha: float = 0.6,
        include_right_axis: bool = True,
        legend_mode: LegendMode = "all",
    ) -> Self:
        """
        Add a legend to the chart.

        This method gathers all available legend entries and renders a
        single consolidated legend on the primary axis. Legend entries may
        originate from plotted series, shaded regions, custom legend items,
        or secondary axis series when present.

        Duplicate labels are automatically removed while preserving the
        order in which legend items were registered.

        Parameters
        ----------
        loc : str, default "upper left"
            Legend location.

        bbox_to_anchor : tuple or None, optional
            Bounding box anchor used to position the legend.

        ncol : int, default 1
            Number of legend columns.

        fontsize : int, default 7
            Legend font size.

        frameon : bool, default True
            Whether to display the legend frame.

        edgecolor : str, default "white"
            Legend frame border color.

        facecolor : str, default "white"
            Legend frame background color.

        framealpha : float, default 0.6
            Legend background transparency.

        include_right_axis : bool, default True
            Whether legend entries from the secondary axis should also
            be included.

        Returns
        -------
        Self
            Returns the chart instance for method chaining.

        Examples
        --------
        Standard legend:

        >>> (
        ...     graph
        ...     .graph_line(spx, label="S&P 500")
        ...     .graph_line(ndx, label="Nasdaq")
        ...     .add_legend()
        ... )

        Combine left and right axis series:

        >>> (
        ...     graph
        ...     .graph_line(price, label="Price")
        ...     .graph_line(rate, axis="right", label="Policy Rate")
        ...     .add_legend()
        ... )

        Place legend outside chart:

        >>> (
        ...     graph
        ...     .add_legend(
        ...         loc="upper center",
        ...         bbox_to_anchor=(0.5, -0.1),
        ...         ncol=3
        ...     )
        ... )
        """

        handles, labels = self._collect_legend_handles_labels(
            include_right_axis=include_right_axis,
            legend_mode=legend_mode,
        )

        final_handles, final_labels = self._deduplicate_legend_handles(
            handles,
            labels,
        )

        if not final_handles:
            return self

        self._ax.legend(
            final_handles,
            final_labels,
            loc=loc,
            bbox_to_anchor=bbox_to_anchor,
            ncol=ncol,
            fontsize=fontsize,
            frameon=frameon,
            edgecolor=edgecolor,
            facecolor=facecolor,
            framealpha=framealpha,
        )

        return self


    def add_legend_point(
        self,
        label: str,
        color: str,
        marker: str = "o",
        markersize: float = 6,
    ) -> Self:
        """
        Register a custom point-style legend item.

        This method creates a legend entry without plotting any data.
        It is useful for displaying events, markers, portfolio positions,
        signals, or annotations that should appear in the legend but are
        not represented by an actual chart series.

        If a legend item with the same label has already been registered,
        the request is ignored to prevent duplicate legend entries.

        Parameters
        ----------
        label : str
            Text displayed in the legend.

        color : str
            Marker color.

        marker : str, default "o"
            Matplotlib marker style.

        markersize : float, default 6
            Marker size displayed in the legend.

        Returns
        -------
        Self
            Returns the chart instance for method chaining.

        Examples
        --------
        Register a custom event marker:

        >>> (
        ...     graph
        ...     .add_legend_point(
        ...         label="Fed Meeting",
        ...         color="red"
        ...     )
        ...     .add_legend()
        ... )

        Use a different marker style:

        >>> (
        ...     graph
        ...     .add_legend_point(
        ...         label="Buy Signal",
        ...         color="green",
        ...         marker="^"
        ...     )
        ...     .add_legend()
        ... )
        """
        if not hasattr(self, "_custom_legend_handles"):
            self._custom_legend_handles = []

        existing_labels = {
            h.get_label()
            for h in self._custom_legend_handles
        }

        if label in existing_labels:
            return self

        self._custom_legend_handles.append(
            Line2D(
                [0],
                [0],
                marker=marker,
                linestyle="None",
                color="none",
                markerfacecolor=color,
                markeredgecolor=color,
                markersize=markersize,
                label=label,
            )
        )

        return self


    def _collect_legend_handles_labels(
        self,
        ax=None,
        include_right_axis: bool = True,
        legend_mode: LegendMode = "all",
    ):
        """
        Collect legend handles and labels from all relevant chart components.

        This helper gathers legend entries from the active axis, the
        secondary axis when available, and any custom legend items
        registered through `add_legend_point()`.

        Parameters
        ----------
        ax : matplotlib.axes.Axes or None, optional
            Axis from which legend entries should be collected. When
            omitted, the active chart axis is used.

        include_right_axis : bool, default True
            Whether legend entries from the secondary axis should
            also be included.

        Returns
        -------
        tuple[list, list]
            A tuple containing:

            - Legend handles.
            - Corresponding legend labels.

        Notes
        -----
        No duplicate filtering is performed by this method.
        """

        target_ax = self._ax if ax is None else ax

        handles, labels = target_ax.get_legend_handles_labels()

        if include_right_axis:

            right_ax = getattr(self, "_right_ax", None)

            if right_ax is not None:
                right_handles, right_labels = (
                    right_ax.get_legend_handles_labels()
                )

                handles.extend(right_handles)
                labels.extend(right_labels)

        custom_handles = getattr(
            self,
            "_custom_legend_handles",
            [],
        )

        if legend_mode == "points":
            handles = (
                self._custom_handles.get(
                    "points",
                    [],
                )
            )

            labels = (
                self._custom_handle_labels.get(
                    "points",
                    [],
                )
            )

            return list(handles), list(labels)

        if custom_handles:
            handles.extend(custom_handles)
            labels.extend(
                handle.get_label()
                for handle in custom_handles
            )

        return handles, labels


    def _deduplicate_legend_handles(self, handles, labels):
        """
        Remove duplicate legend entries while preserving order.

        This helper keeps only the first occurrence of each legend label.
        Empty labels and internal Matplotlib labels beginning with "_"
        are automatically ignored.

        Parameters
        ----------
        handles : list
            Legend handles.

        labels : list[str]
            Legend labels.

        Returns
        -------
        tuple[list, list]
            Deduplicated handles and labels ready to be passed to
            `Axes.legend()`.

        Notes
        -----
        Matplotlib allows multiple artists with identical labels.
        This helper ensures that only one entry per unique label
        appears in the final legend.
        """
        final_handles = []
        final_labels = []
        seen = set()

        for handle, label in zip(handles, labels):
            if label is None or label == "" or label.startswith("_"):
                continue

            if label in seen:
                continue

            final_handles.append(handle)
            final_labels.append(label)
            seen.add(label)

        return final_handles, final_labels
