from __future__ import annotations
from matplotlib.lines import Line2D
from typing import Self

class LegendMixin:
    """
    Provide legend registration, handle collection, and rendering.
    """
    def add_legend(
            self,
            show: bool = False,
            loc: str = "upper left",
            bbox_to_anchor: tuple = None,
            ncol: int = 1,
            fontsize: int = 7,
            frameon: bool = True,
            edgecolor: str = "white",
            facecolor: str = "white",
            framealpha: float = 0.6
    ) -> Self:
        """
        Add and style a legend for the active axis.

        This method combines legend handles generated by Matplotlib with optional
        custom legend handles registered through helper methods. Duplicate labels
        are removed while preserving their original order.

        Parameters
        ----------
        show : bool, default False
            Whether to display the legend.
        loc : str, default "upper left"
            Legend location.
        bbox_to_anchor : tuple or None, optional
            Optional bounding box anchor used to position the legend.
        ncol : int, default 3
            Number of legend columns.
        fontsize : int, default 7
            Legend font size.
        frameon : bool, default True
            Whether to display the legend frame.
        edgecolor : str, default "white"
            Legend frame edge color.
        facecolor : str, default "white"
            Legend frame background color.
        framealpha : float, default 0.6
            Legend frame transparency.

        Returns
        -------
        None
            The legend is added directly to the active axis when available.
        """

        if not show:
            return self

        handles, labels = self._ax.get_legend_handles_labels()

        custom_handles = getattr(self, "_custom_legend_handles", None)

        if custom_handles:
            handles = handles + custom_handles
            labels = labels + [h.get_label() for h in custom_handles]

        # -------------------------------------------------
        # Evitar duplicados preservando orden
        # -------------------------------------------------
        final_handles = []
        final_labels = []
        seen = set()

        for h, lab in zip(handles, labels):
            if lab is None or lab == "" or lab.startswith("_"):
                continue

            if lab in seen:
                continue

            final_handles.append(h)
            final_labels.append(lab)
            seen.add(lab)

        if len(final_handles) == 0:
            return self

        self._ax.legend(
            final_handles,
            final_labels,
            loc=loc,
            bbox_to_anchor=bbox_to_anchor,
            ncol=ncol,
            fontsize=fontsize,
            frameon=frameon,
            edgecolor=edgecolor,
            facecolor=facecolor,
            framealpha=framealpha
        )

        return self


    def add_legend_point(
        self,
        label: str,
        color: str,
        marker: str = "o",
        markersize: float = 6,
    ) -> Self:
        
        """
        Register a custom point-style legend item for the active axis.

        Notes
        -----
        This docstring was added during the modular refactor to make the API easier
        to understand for new users and maintainers.
        """
        if not hasattr(self, "_custom_legend_handles"):
            self._custom_legend_handles = []

        existing_labels = {
            h.get_label()
            for h in self._custom_legend_handles
        }

        if label in existing_labels:
            return self

        self._custom_legend_handles.append(
            Line2D(
                [0],
                [0],
                marker=marker,
                linestyle="None",
                color="none",
                markerfacecolor=color,
                markeredgecolor=color,
                markersize=markersize,
                label=label,
            )
        )

        return self


    def _collect_legend_handles_labels(
        self,
        ax=None,
        include_right_axis: bool = True,
    ):
        target_ax = self._ax if ax is None else ax

        handles, labels = target_ax.get_legend_handles_labels()

        if include_right_axis and getattr(self, "_right_ax", None) is not None:
            right_handles, right_labels = self._right_ax.get_legend_handles_labels()
            handles = handles + right_handles
            labels = labels + right_labels

        custom_handles = getattr(self, "_custom_legend_handles", None)
        if custom_handles:
            handles = handles + custom_handles
            labels = labels + [
                handle.get_label()
                for handle in custom_handles
            ]

        return handles, labels


    def _deduplicate_legend_handles(self, handles, labels):
        final_handles = []
        final_labels = []
        seen = set()

        for handle, label in zip(handles, labels):
            if label is None or label == "" or label.startswith("_"):
                continue

            if label in seen:
                continue

            final_handles.append(handle)
            final_labels.append(label)
            seen.add(label)

        return final_handles, final_labels