site_name: Helpers PS
site_url: https://jc-ocampob.github.io/Helpers_PS/
site_description: Documentación interna del paquete Helpers PS
site_author: Equipo de Soluciones de Portafolio

theme:
  name: material
  language: es
  palette:
    - scheme: default
      primary: black
      accent: blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    - scheme: slate
      primary: black
      accent: blue
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.highlight
    - search.suggest
    - content.code.copy
    - content.code.select

plugins:
  - search
  - mkdocs-jupyter
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          options:
            docstring_style: numpy
            show_source: true
            show_root_heading: true
            show_root_full_path: false
            show_signature_annotations: true
            members_order: source

markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - tables
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.tabbed:
      alternate_style: true

nav:
  - Index: index.md
  
  - Instalation: install_guide.md
  
  - GraphMtplt:
    - Getting Started: GraphMtplt/getting_started.ipynb
    
    - Line Chart: 
      - Graph: GraphMtplt/Line/graph.ipynb
      - Tags: GraphMtplt/Line/tags.ipynb
      - Examples:
        - Simple Line: GraphMtplt/Line/examples/simple_line.ipynb 
        - Tags Usage: GraphMtplt/Line/examples/tags.ipynb
      
    - Bar Chart:
      - Graph: GraphMtplt/Bar/graph.md
    
    - Pie Chart:
      - Graph: GraphMtplt/Pie/graph.md

    - Box Whiskers Chart:
      - Graph: GraphMtplt/Box/graph.md
    
    - Utils:
      - Utils: GraphMtplt/Utils/utils.md

  - FinCalculations:
    - Getting Started: FinCalculations/getting_started.md
  
  - Powerpoint:
    - Getting Started: Powerpoint/getting_started.md
  
  - Excel:
    - Getting Started: Excel/getting_started.md
